version: 0.2

env:
  variables:
    DOCKER_BUILD_IMAGE: 259525371233.dkr.ecr.us-east-2.amazonaws.com/test
    ECSSTACK: ecs-trivial-cluster
    APP_NAME: ecs-trivial-tomcat
    APP_PORT: 8080
    APP_LB_PRIORITY: 100

phases:
  pre_build:
    commands:
      ### ENVIRONMENT PREP ###
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REV=$(git rev-parse --short HEAD)
  build:
    commands:
      ### BUILD YOUR WAR FILE ###
      - echo "Maven build code here"
      - cd src
      - mvn -q clean install
      - cp target/HelloWorld-1.0.war  .
      - cd ..
  post_build:
    commands:
      ### BUILD THE DOCKER IMAGE ###
      - docker build -t "${APP_NAME}" src
      - docker tag "${APP_NAME}":latest "${DOCKER_BUILD_IMAGE}":"${REV}"
      - docker tag "${APP_NAME}":latest "${DOCKER_BUILD_IMAGE}":latest
      - docker push "${DOCKER_BUILD_IMAGE}":"${REV}"
      - docker push "${DOCKER_BUILD_IMAGE}":latest
      ### DEPLOY THE ECS SERVICE ###
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file app-deployment.yaml --stack-name "${APP_NAME}" --parameter-overrides ECSStackName="${ECSSTACK}" ExampleAppImagePath="${DOCKER_BUILD_IMAGE}" ExampleAppImageTag="${REV}" ExampleAppInsidePort="${APP_PORT}" ExampleAppLoadBalancerPriority="${APP_LB_PRIORITY}"
