version: 0.2
env:
  git-credential-helper: yes
  variables:
    DOCKER_BUILD_IMAGE: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
    APP_NAME: ecs-trivial-tomcat
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      ### ENVIRONMENT PREP ###
      - java --version
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REV=$(git rev-parse --short https://github.com/mamvai/ecs-trivial-tomcat.git)
  build:
    commands:
      ### BUILD YOUR WAR FILE ###
      - echo "Maven build code here"
      - cd src
      - mvn -q clean install
      - cp target/HelloWorld-1.0.war  .
      - cd ..

  post_build:
    commands:
      ### BUILD THE DOCKER IMAGE ###
      - DOCKER_BUILD_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - docker build -t "${APP_NAME}" src
      #- docker tag "${APP_NAME}":latest "${DOCKER_BUILD_IMAGE}":"${REV}"
      - docker tag "${APP_NAME}":latest "${DOCKER_BUILD_IMAGE}":latest
      #- docker push "${DOCKER_BUILD_IMAGE}":"${REV}"
      - docker push "${DOCKER_BUILD_IMAGE}":latest
      - echo Writing image definitions file...
      - printf '[{"name":"exampleapp","imageUri":"%s"}]' ${DOCKER_BUILD_IMAGE} > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
